# Generated by Django 4.1.3 on 2022-12-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_name', models.CharField(help_text='Enter name of the committee', max_length=20, unique=True)),
                ('Committee_Department', models.CharField(help_text='Enter deparment of the committee', max_length=20)),
                ('Committee_Logo', models.ImageField(upload_to='CommitteLogo/')),
                ('Committee_date_of_establishment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_name', models.CharField(help_text='Enter the name of position', max_length=20)),
                ('Position_for', models.CharField(choices=[('Core', 'Core'), ('CoCom', 'CoCom')], max_length=20)),
                ('Committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Position_Committee', to='Committee.committee')),
            ],
            options={
                'unique_together': {('Committee', 'Position_name', 'Position_for')},
            },
        ),
    ]
