# Generated by Django 4.1.3 on 2022-12-29 15:04

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('First_name', models.CharField(help_text='Enter your First name', max_length=20)),
                ('Last_name', models.CharField(help_text='Enter your Last name', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Enter your Date of Birth')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter Phone Number', max_length=128, region=None, unique=True)),
                ('department', models.CharField(help_text='Enter your deparment', max_length=20)),
                ('email', models.EmailField(help_text='Enter your Email', max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Committee_name', models.CharField(help_text='Enter name of the committee', max_length=20, unique=True)),
                ('Committee_Department', models.CharField(help_text='Enter deparment of the committee', max_length=20)),
                ('Committee_Logo', models.ImageField(upload_to='CommitteLogo/')),
                ('Committee_date_of_establishment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_name', models.CharField(help_text='Enter the name of position', max_length=20)),
                ('Position_for', models.CharField(choices=[('Core', 'Core'), ('CoCom', 'CoCom')], max_length=20)),
                ('Committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Position_Committee', to='accounts.committee')),
            ],
            options={
                'unique_together': {('Committee', 'Position_name', 'Position_for')},
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Enter your Designation', max_length=20)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guide_Committee', to='accounts.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guide_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'committee')},
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Core_Committee', to='accounts.committee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Core_Position', to='accounts.position', validators=[accounts.models.Core.positionValidator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Core_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'committee', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CoCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoCom_Committee', to='accounts.committee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoCom_Position', to='accounts.position', validators=[accounts.models.CoCom.positionValidator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoCom_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'committee', 'position')},
            },
        ),
    ]
